backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "hujan"
    label: "Update Data Hujan"
    folder: "data/hujan"
    create: true
    slug: "{{year}}"
    extension: "json"
    format: "json"
    fields:
      - { label: "Tahun", name: "year", widget: "string", hint: "Contoh: 2026" }
      - { label: "01. Kemayoran", name: "st_01", widget: "number", value_type: "float", default: 0 }
      - { label: "02. Halim", name: "st_02", widget: "number", value_type: "float", default: 0 }
      - { label: "03. Bogor", name: "st_03", widget: "number", value_type: "float", default: 0 }
      - { label: "04. Banten", name: "st_04", widget: "number", value_type: "float", default: 0 }
      - { label: "05. Katulampa", name: "st_05", widget: "number", value_type: "float", default: 0 }
      - { label: "06. Depok", name: "st_06", widget: "number", value_type: "float", default: 0 }
      - { label: "07. Manggarai", name: "st_07", widget: "number", value_type: "float", default: 0 }
      - { label: "08. Karet", name: "st_08", widget: "number", value_type: "float", default: 0 }
      - { label: "09. Setiabudi Timur", name: "st_09", widget: "number", value_type: "float", default: 0 }
      - { label: "10. Melati", name: "st_10", widget: "number", value_type: "float", default: 0 }
      - { label: "11. Istana", name: "st_11", widget: "number", value_type: "float", default: 0 }
      - { label: "12. Krukut Hulu", name: "st_12", widget: "number", value_type: "float", default: 0 }
      - { label: "13. Sunter Hulu", name: "st_13", widget: "number", value_type: "float", default: 0 }
      - { label: "14. Pesanggrahan", name: "st_14", widget: "number", value_type: "float", default: 0 }
      - { label: "15. Angke Hulu", name: "st_15", widget: "number", value_type: "float", default: 0 }
      - { label: "16. Tanjungan", name: "st_16", widget: "number", value_type: "float", default: 0 }
      - { label: "17. Tomang Barat", name: "st_17", widget: "number", value_type: "float", default: 0 }
      - { label: "18. Teluk Gong", name: "st_18", widget: "number", value_type: "float", default: 0 }
      - { label: "19. Pulo Gadung", name: "st_19", widget: "number", value_type: "float", default: 0 }
      - { label: "20. Sunter Kodamar", name: "st_20", widget: "number", value_type: "float", default: 0 }
      - { label: "21. Sunter III Rawa Badak", name: "st_21", widget: "number", value_type: "float", default: 0 }
      - { label: "22. Pompa Cideng", name: "st_22", widget: "number", value_type: "float", default: 0 }
      - { label: "Keterangan/Catatan", name: "body", widget: "text", required: false }
